name: Deploy Theme to Shopify

on:
  push:
    branches:
      - main
    paths:
      - 'theme/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Shopify
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Deploy theme to Shopify
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_SHOP }}
        run: |
          shopify theme push --path theme --theme ${{ secrets.SHOPIFY_THEME_ID }} --nodelete --allow-live
